# Generated by Django 4.2.18 on 2025-01-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
